version: '3'
services:
  iam:
    container_name: ark-center-auth
    image: ark-center-auth:1.0.0
    restart: always
    ports:
      - "8089:8089"
    env_file:
      - start.env
    networks:
      - "compose_default"
networks:
  compose_default:
    external: true