server:
  port: 8080
spring:
  application:
    name: iam
  datasource:
    druid:
      url: jdbc:mysql://gz-cynosdbmysql-grp-irl7x9ar.sql.tencentcdb.com:20716/iam?useSSL=false&useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&serverTimezone=UTC&allowPublicKeyRetrieval=True
      username: kt_cloud8888
      password: Kt.cloud1234!@#$
      name: defaultDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 100
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-idle: 10
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true
# mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
ark:
  security:
    allow-list:
      - /iam/auth/login
      - /iam/auth/logout
      - /iam/auth/kick
      - /iam/api/init
      - /iam/user/permission/check
      - /iam/alert/*
      - /iam/docker

logging:
  level:
    root: info
