apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-ark-center-iam
  labels:
    app: dep-ark-center-iam
spec:
  replicas: 1
  template:
    metadata:
      name: dep-ark-center-iam
      labels:
        app: dep-ark-center-iam
    spec:
      containers:
        - name: dep-ark-center-iam
          image: ark-center-iam:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NACOS_DISCOVERY_IP
              value: 192.168.84.194
            - name: NACOS_DISCOVERY_SERVER_ADDR
              value: nacos.cloud.org:8848
            - name: NACOS_CONFIG_SERVER_ADDR
              value: nacos.cloud.org:8848
            - name: SYS_OPT
              value: "-DSpring.profiles.active=dev"
            - name: LANG
              value: "C.UTF-8"
            - name: TZ
              value: "Asia/Shanghai"
      restartPolicy: Always
  selector:
    matchLabels:
      app: dep-ark-center-iam
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ark-center-iam
spec:
  selector:
    app: dep-ark-center-iam
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort