server:
  port: 8080
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://mysql.ark.com:3306/auth?useSSL=false&useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&serverTimezone=UTC&allowPublicKeyRetrieval=True
    username: root
    password: root
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
# mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
ark:
  security:
    allow-list:
      - /auth/auth/login
      - /auth/auth/logout
      - /auth/auth/kick
      - /auth/api/init
      - /auth/user/permission/check
      - /auth/alert/*
      - /auth/docker

logging:
  level:
    root: info
