server:
  port: 10001
  servlet:
    context-path: /upms
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/kt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: Root1234!@#$
    druid:
      pool-prepared-statements: true
      initial-size: 10
      max-active: 50
      min-idle: 2
      max-wait: 60000
      filters: stat
      test-on-borrow: false
      test-while-idle: false
      test-on-return: false
      query-timeout: 0
      transaction-query-timeout: 0
      login-timeout: 0
      validation-query: select 1 from dual
      validation-query-timeout: 1
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 8
        time-between-eviction-runs:
    timeout: 2000
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${server.port}
      host: localhost
      port: 8500
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  mapper-locations: classpath*:/com/kt/upms/**/mapper/impl/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  type-aliases-package: com.sunrise.esaleb.tbs.domain
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000 # feign 的超时设置
        readTimeout: 20000
logging:
  config: classpath:logback-spring.xml
esaleb:
  security:
    login:
      # 开发环境使用db模式存储token比较方便，测试和生产环境替换成redis
      token-storage-strategy: redis

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
